In [125]:
# importing libraries
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.common.keys import Keys
from bs4 import BeautifulSoup
from time import sleep
import pandas as pd

In [86]:
# opeing chrome browser  with the help of webdriver
driver = webdriver.Chrome(executable_path= r"C:\api\chromedriver.exe")
driver.maximize_window() #maximising the window

C:\Users\Deepak Verma\AppData\Local\Temp\ipykernel_9708\2220181946.py:1: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver = webdriver.Chrome(executable_path= r"C:\api\chromedriver.exe")

In [87]:
#here you can change python with the multiple skills to get the jobs related to that skill only
driver.get('https://www.instahyre.com/python-jobs')

In [88]:
'''Here I am making one fucntion whihc will take soup of company as a input and return all the info of 
that company in the form of dictonary'''
def find_info(soup_of_company):
    try:
        company_name =  soup_of_company.find('div', class_="employer-job-name").text.strip()
    except:
        company_name = "not given"
    try:
        loc = soup_of_company.find('div', class_="employer-locations").text.strip()
    except:
        loc = "not given"
    try:
        founded, employees = soup_of_company.find('div', class_="employer-info").text.strip().split('\n\nâ€¢\n\n')
    except:
        founded, employees = "not given", "not given"
    try:
        about = soup_of_company.find('div', class_="employer-notes ng-binding ng-scope").text.strip()
    except:
        about = "not given"
    try:
        skills = ",".join([i. text for i in soup_of_company.find('div', class_="job-skills ng-scope").find_all("li")])
    except:
        skills = "not given"
    try:
        link = soup_of_company.find('a', href = True)['href']
    except:
        link = "not given"
    return {"name":company_name, 'location': loc, "founded": founded, "employees": employees, "about":about, "skills": skills, 'link': link }

In [126]:
# here is simple code to get the soup of all company for 50 pages
job_list = []
for i in range (50):
    if i>=1:
        driver.find_element(By.XPATH, "/html/body/div[2]/div[1]/div[2]/div[2]/div/div[1]/div[1]/div[11]/li[12]").click()
        sleep(3)
    html = driver.page_source
    soup = BeautifulSoup(html)
    list_comp = soup.find_all("div", class_ = "employer-row")
    job_list += list_comp
    print(f"page {i} extracted sucessfully")

page 0 extracted sucessfully
page 1 extracted sucessfully
page 2 extracted sucessfully
page 3 extracted sucessfully
page 4 extracted sucessfully
page 5 extracted sucessfully
page 6 extracted sucessfully
page 7 extracted sucessfully
page 8 extracted sucessfully
page 9 extracted sucessfully
page 10 extracted sucessfully
page 11 extracted sucessfully
page 12 extracted sucessfully
page 13 extracted sucessfully
page 14 extracted sucessfully
page 15 extracted sucessfully
page 16 extracted sucessfully
page 17 extracted sucessfully
page 18 extracted sucessfully
page 19 extracted sucessfully
page 20 extracted sucessfully
page 21 extracted sucessfully
page 22 extracted sucessfully
page 23 extracted sucessfully
page 24 extracted sucessfully
page 25 extracted sucessfully
page 26 extracted sucessfully
page 27 extracted sucessfully
page 28 extracted sucessfully
page 29 extracted sucessfully
page 30 extracted sucessfully
page 31 extracted sucessfully
page 32 extracted sucessfully
page 33 extracted sucessfully
page 34 extracted sucessfully
page 35 extracted sucessfully
page 36 extracted sucessfully
page 37 extracted sucessfully
page 38 extracted sucessfully
page 39 extracted sucessfully
page 40 extracted sucessfully
page 41 extracted sucessfully
page 42 extracted sucessfully
page 43 extracted sucessfully
page 44 extracted sucessfully
page 45 extracted sucessfully
page 46 extracted sucessfully
page 47 extracted sucessfully
page 48 extracted sucessfully
page 49 extracted sucessfully

In [127]:
# creating pandas dataframe with the soup we are getting 
df = pd.DataFrame(job_list, columns = ['sep1', 'main', 'sep2'])

C:\ProgramData\anaconda3\lib\site-packages\pandas\core\internals\construction.py:568: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  values = np.array([convert(v) for v in values])

In [128]:
# extracting info of the dictonary and creating multiple columns out of it
df[['name', 'location', 'founded', 'employees', 'about', 'skills', 'link']] = df['main'].apply(lambda x: pd.Series(find_info(x)))

In [129]:
# droping useless columns from the dataframe
df.drop(columns = ['sep1', 'main', 'sep2'], inplace = True)

In [130]:
# here is the final dataframe
df

,name,location,founded,employees,about,skills,link
0,Adagrad AI - C++ Developer,Job available in Pune,Founded in 2018,10 - 50 employees,Adagrad AI is a leading AI solution provider t...,"Python,C++,C,CI - CD,Algorithms",https://www.instahyre.com/job-276192-c-develop...
1,Adagrad AI - Python Django Developer,Job available in Pune,Founded in 2018,10 - 50 employees,Adagrad AI is a leading AI solution provider t...,"Python,Django,SQL,AWS",https://www.instahyre.com/job-276197-python-dj...
2,Avis Budget Group - Senior Data Platform Engineer,Job available in Bangalore,Founded in 1946,More than 1000 employees,Avis Budget is a global mobility solutions com...,"Python,Data Analysis,Linux,Google Cloud,CI - CD",https://www.instahyre.com/job-276154-senior-da...
3,Omnivio - Data Analyst,Job available in Noida,Founded in 2021,10 - 50 employees,Omnivio is a logistics and supply-chain compan...,"Python,SQL,Data Analysis,Supply Chain Manageme...",https://www.instahyre.com/job-276191-data-anal...
4,Our Sunday Visitor - Full - Stack Developer,Job available in Gurgaon,Founded in 1912,200 - 500 employees,not given,"Python,React.js,Django,Redux,MongoDB",https://www.instahyre.com/job-276152-full-stac...
...,...,...,...,...,...,...,...
495,Medtronic - Product Security Engineer,Job available in Hyderabad,Founded in 1949,More than 1000 employees,not given,"Python,Vulnerability Assessment,Information Se...",https://www.instahyre.com/job-270486-product-s...
496,Nykaa - SDE 3 / Lead Engineer,Job available in Gurgaon,Founded in 2012,200 - 500 employees,Nykaa is an eCommerce store focused on beauty ...,"Python,Data Structures,Algorithms,DevOps,Java",https://www.instahyre.com/job-270484-sde-3-lea...
497,Splore - Lead - Data - AI & NLP,Job available in Bangalore,Founded in 2023,10 - 50 employees,Splore is an AI company that is re-imagining e...,"Python,Machine Learning,NLP,Data Modelling",https://www.instahyre.com/job-270373-lead-data...
498,Splore - Lead AI and NLP Engineer,Job available in Bangalore,Founded in 2023,10 - 50 employees,Splore is an AI company that is re-imagining e...,"Python,NLP,Machine Learning,TensorFlow,MLOps",https://www.instahyre.com/job-270451-lead-ai-a...
499,Teradata - Data Engineer - Azure Databricks,"Job available in Mumbai, Pune",Founded in 1980,More than 1000 employees,Teradata is a provider of database-related pro...,"Python,Azure,Azure Data Factory,Databricks,PyS...",https://www.instahyre.com/job-270494-data-engi...